gpio_out: 26 # pin used to transmit rf codes
devices: # devices
    - device: lights
      on_code: 5526835
      off_code: 5526844
      pulse_length: 24
      remote_key: 1 # number on remote corresponding to rf switch
    - device: fan
      on_code: 5526979
      off_code: 5526988
      pulse_length: 24
      remote_key: 2
